Test 2
miyu-40/mokumoku pull request #2
Opened 2023-04-12 17:08 UTC by miyu-40

以下の実装を行いました。
- ユーザー登録時に手入力やチェックボックス入力ではなく、セレクト形式で性別登録できる。
- イベント作成画面にOnly womanのチェックボックスにチェックを入れるだけで女性限定イベントを作できる。
- ユーザーが女性以外の場合、イベント作成時にOnly womanは表示されず、女性限定イベントが作成できない。
- 女性限定イベントには女性のみが参加できる。
- 女性以外の場合、女性限定イベントの詳細ページを開いた際に「このもくもく会に参加する」が表示されない。
- 女性限定イベントは一覧・詳細画面にて「女性限定」が表記される。

また、RSpecのテスト結果のスクリーンショットです。
[![Image from Gyazo](https://i.gyazo.com/eef1c76e48235f87ce4781a7c94fd26c.png)](https://gyazo.com/eef1c76e48235f87ce4781a7c94fd26c)
ご確認よろしくお願いいたします。

2023-04-13 10:54 UTC, busitora requested changes
コメントしました！

2023-04-13 10:54 UTC, busitora commented on app/controllers/events/attendances_controller.rb
> +    if current_user.not_woman_event?(@event.only_woman == true)
6-10行目はモデルに寄せてください〜！

2023-04-13 10:54 UTC, busitora commented on app/controllers/events_controller.rb
> +    if current_user.not_woman_event?(event_params[:only_woman])
ここもモデルに寄せてください〜！

2023-04-13 10:54 UTC, busitora commented on app/models/user.rb
> +  def not_woman_event?(only_woman)
try point (必須ではないです) 

ド・モルガンの法則で調べてみて下さい！
リファクタの余地があります

2023-04-13 10:54 UTC, busitora commented on app/views/events/show.html.erb
> +                  <% unless @event.only_woman && current_user.man? || current_user.other? %>
モデルに寄せてください〜

2023-04-13 14:53 UTC, miyu-40 commented on app/controllers/events/attendances_controller.rb
> +    if current_user.not_woman_event?(@event.only_woman == true)
ご確認ありがとうございます！
[7b77f82](https://github.com/miyu-40/mokumoku/pull/2/commits/7b77f828026e60cf58fac07a05c7297d0424eedf)
こちらで修正いたしました。

2023-04-13 14:56 UTC, miyu-40 commented on app/controllers/events_controller.rb
> +    if current_user.not_woman_event?(event_params[:only_woman])
[f52b485](https://github.com/miyu-40/mokumoku/pull/2/commits/f52b4855ef129bea175603d360111b4594914845)
こちらで修正いたしました。

2023-04-13 14:57 UTC, miyu-40 commented on app/models/user.rb
> +  def not_woman_event?(only_woman)
[7b77f82](https://github.com/miyu-40/mokumoku/pull/2/commits/7b77f828026e60cf58fac07a05c7297d0424eedf)
こちらで修正いたしました。

2023-04-13 14:57 UTC, miyu-40 commented on app/views/events/show.html.erb
> +                  <% unless @event.only_woman && current_user.man? || current_user.other? %>
[bcdaad0](https://github.com/miyu-40/mokumoku/pull/2/commits/bcdaad0e0699f829b117e656c32711865609242b)
こちらで修正いたしました。

2023-04-14 10:49 UTC, takyyk commented
@miyu-40 
LGTMです！

2023-04-14 12:21 UTC, merged